const { Painting } = require('../models');

const paintingdata = [
  {
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A01-image.jpg',
    description:'Anime',
  },
  {
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A02-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A03-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A04-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A05-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A06-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A07-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A08-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A09-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A10-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A11-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A12-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A13-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A14-image.png',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A15-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A16-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A17-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A18-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A19-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: 'A20-image.png',
    description:'Anime',
  },
  {
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L01-image.jpg',
    description: 'Landscapes',
  },
  {
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L02-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L03-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L04-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L05-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L06-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L07-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L08-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L09-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L10-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L11-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L12-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L13-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L14-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L15-image.png',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L16-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L17-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L18-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L19-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: 'L20-image.jpg',
    description: 'Landscapes',
  },
  {
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH01-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH02-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH03-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH04-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH05-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH06-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH07-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH08-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH09-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH10-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH11-image.jpg',
    description: 'Photography',
  },
  {
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: 'PH12-image.jpg',
    description: 'Photography',
  },
  {
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P01-image.jpg',
    description: 'Portrait',
  },
  {
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P02-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P03-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P04-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P05-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P06-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P07-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P08-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P09-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P10-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P11-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P12-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P13-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P14-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P15-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P16-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P17-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P18-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P19-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: 'P20-image.jpg',
    description: 'Portrait',
  },
 
];

const seedPaintings = () => Painting.bulkCreate(paintingdata);

module.exports = seedPaintings;
