const { Painting } = require('../models');

const paintingdata = [
  {
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A01-image.jpg',
    description:'Anime',
  },
  {
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A02-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A03-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A04-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A05-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A06-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A07-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A08-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A09-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A10-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A11-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A12-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A13-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A14-image.png',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A15-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A16-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A17-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A18-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A19-image.jpg',
    description:'Anime',
  },{
    title: 'Anime',
    artist: 'Unknown',
    gallery_id: 1,
    filename: '/images/Anime/A20-image.png',
    description:'Anime',
  },
  {
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L01-image.jpg',
    description: 'Landscapes',
  },
  {
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L02-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L03-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L04-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L05-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L06-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L07-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L08-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L09-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L10-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L11-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L12-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L13-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L14-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L15-image.png',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L16-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L17-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L18-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L19-image.jpg',
    description: 'Landscapes',
  },{
    title: 'Lanscapes',
    artist: 'Unknown',
    gallery_id: 2,
    filename: '/images/Landscapes/L20-image.jpg',
    description: 'Landscapes',
  },
  {
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH01-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH02-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH03-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH04-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH05-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH06-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH07-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH08-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH09-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH10-image.jpg',
    description: 'Photography',
  },{
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH11-image.jpg',
    description: 'Photography',
  },
  {
    title: 'Photography',
    artist: 'Unknown',
    gallery_id: 3,
    filename: '/images/Photography/PH12-image.jpg',
    description: 'Photography',
  },
  {
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P01-image.jpg',
    description: 'Portrait',
  },
  {
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P02-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P03-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P04-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P05-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P06-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P07-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P08-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P09-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P10-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P11-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P12-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P13-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P14-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P15-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P16-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P17-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P18-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P19-image.jpg',
    description: 'Portrait',
  },{
    title: 'Portraits',
    artist: 'Unknown',
    gallery_id: 4,
    filename: '/images/Portraits/P20-image.jpg',
    description: 'Portrait',
  },
 
];

const seedPaintings = async () => await Painting.bulkCreate(paintingdata);

module.exports = seedPaintings;
